// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TTIM.proto

package cn.dmandp.common;

public final class TTIM {
    private TTIM() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_TTUser_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_TTUser_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_TTMessage_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_TTMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\nTTIM.proto\"Y\n\006TTUser\022\013\n\003uId\030\001 \001(\005\022\r\n\005u" +
                        "Name\030\002 \001(\t\022\016\n\006uPhoto\030\003 \001(\t\022\021\n\tuPassword\030" +
                        "\004 \001(\t\022\020\n\010uFriends\030\005 \003(\005\"L\n\tTTMessage\022\020\n\010" +
                        "mContent\030\001 \001(\t\022\r\n\005mTime\030\002 \001(\004\022\017\n\007mFromId" +
                        "\030\003 \001(\005\022\r\n\005mToId\030\004 \001(\005B\024\n\020cn.dmandp.commo" +
                        "nP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_TTUser_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_TTUser_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_TTUser_descriptor,
                new java.lang.String[]{"UId", "UName", "UPhoto", "UPassword", "UFriends",});
        internal_static_TTMessage_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_TTMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_TTMessage_descriptor,
                new java.lang.String[]{"MContent", "MTime", "MFromId", "MToId",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
