// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TTIM.proto

package cn.dmandp.entity;

/**
 * Protobuf type {@code TTMessage}
 */
public final class TTMessage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:TTMessage)
        TTMessageOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use TTMessage.newBuilder() to construct.
    private TTMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private TTMessage() {
        mContent_ = "";
        mTime_ = 0L;
        mFromId_ = 0;
        mToId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private TTMessage(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        mContent_ = s;
                        break;
                    }
                    case 16: {

                        mTime_ = input.readUInt64();
                        break;
                    }
                    case 24: {

                        mFromId_ = input.readInt32();
                        break;
                    }
                    case 32: {

                        mToId_ = input.readInt32();
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cn.dmandp.entity.TTIM.internal_static_TTMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cn.dmandp.entity.TTIM.internal_static_TTMessage_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.dmandp.entity.TTMessage.class, cn.dmandp.entity.TTMessage.Builder.class);
    }

    public static final int MCONTENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object mContent_;

    /**
     * <code>string mContent = 1;</code>
     */
    public java.lang.String getMContent() {
        java.lang.Object ref = mContent_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            mContent_ = s;
            return s;
        }
    }

    /**
     * <code>string mContent = 1;</code>
     */
    public com.google.protobuf.ByteString
    getMContentBytes() {
        java.lang.Object ref = mContent_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            mContent_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int MTIME_FIELD_NUMBER = 2;
    private long mTime_;

    /**
     * <code>uint64 mTime = 2;</code>
     */
    public long getMTime() {
        return mTime_;
    }

    public static final int MFROMID_FIELD_NUMBER = 3;
    private int mFromId_;

    /**
     * <code>int32 mFromId = 3;</code>
     */
    public int getMFromId() {
        return mFromId_;
    }

    public static final int MTOID_FIELD_NUMBER = 4;
    private int mToId_;

    /**
     * <code>int32 mToId = 4;</code>
     */
    public int getMToId() {
        return mToId_;
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getMContentBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mContent_);
        }
        if (mTime_ != 0L) {
            output.writeUInt64(2, mTime_);
        }
        if (mFromId_ != 0) {
            output.writeInt32(3, mFromId_);
        }
        if (mToId_ != 0) {
            output.writeInt32(4, mToId_);
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getMContentBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mContent_);
        }
        if (mTime_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeUInt64Size(2, mTime_);
        }
        if (mFromId_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, mFromId_);
        }
        if (mToId_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(4, mToId_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof cn.dmandp.entity.TTMessage)) {
            return super.equals(obj);
        }
        cn.dmandp.entity.TTMessage other = (cn.dmandp.entity.TTMessage) obj;

        boolean result = true;
        result = result && getMContent()
                .equals(other.getMContent());
        result = result && (getMTime()
                == other.getMTime());
        result = result && (getMFromId()
                == other.getMFromId());
        result = result && (getMToId()
                == other.getMToId());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + MCONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getMContent().hashCode();
        hash = (37 * hash) + MTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getMTime());
        hash = (37 * hash) + MFROMID_FIELD_NUMBER;
        hash = (53 * hash) + getMFromId();
        hash = (37 * hash) + MTOID_FIELD_NUMBER;
        hash = (53 * hash) + getMToId();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static cn.dmandp.entity.TTMessage parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.dmandp.entity.TTMessage parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.dmandp.entity.TTMessage parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.dmandp.entity.TTMessage parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.dmandp.entity.TTMessage parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.dmandp.entity.TTMessage parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.dmandp.entity.TTMessage parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.dmandp.entity.TTMessage parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.dmandp.entity.TTMessage parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.dmandp.entity.TTMessage parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.dmandp.entity.TTMessage parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.dmandp.entity.TTMessage parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(cn.dmandp.entity.TTMessage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code TTMessage}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:TTMessage)
            cn.dmandp.entity.TTMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.dmandp.entity.TTIM.internal_static_TTMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.dmandp.entity.TTIM.internal_static_TTMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.dmandp.entity.TTMessage.class, cn.dmandp.entity.TTMessage.Builder.class);
        }

        // Construct using cn.dmandp.entity.TTMessage.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            mContent_ = "";

            mTime_ = 0L;

            mFromId_ = 0;

            mToId_ = 0;

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return cn.dmandp.entity.TTIM.internal_static_TTMessage_descriptor;
        }

        public cn.dmandp.entity.TTMessage getDefaultInstanceForType() {
            return cn.dmandp.entity.TTMessage.getDefaultInstance();
        }

        public cn.dmandp.entity.TTMessage build() {
            cn.dmandp.entity.TTMessage result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public cn.dmandp.entity.TTMessage buildPartial() {
            cn.dmandp.entity.TTMessage result = new cn.dmandp.entity.TTMessage(this);
            result.mContent_ = mContent_;
            result.mTime_ = mTime_;
            result.mFromId_ = mFromId_;
            result.mToId_ = mToId_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cn.dmandp.entity.TTMessage) {
                return mergeFrom((cn.dmandp.entity.TTMessage) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(cn.dmandp.entity.TTMessage other) {
            if (other == cn.dmandp.entity.TTMessage.getDefaultInstance()) return this;
            if (!other.getMContent().isEmpty()) {
                mContent_ = other.mContent_;
                onChanged();
            }
            if (other.getMTime() != 0L) {
                setMTime(other.getMTime());
            }
            if (other.getMFromId() != 0) {
                setMFromId(other.getMFromId());
            }
            if (other.getMToId() != 0) {
                setMToId(other.getMToId());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            cn.dmandp.entity.TTMessage parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (cn.dmandp.entity.TTMessage) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private java.lang.Object mContent_ = "";

        /**
         * <code>string mContent = 1;</code>
         */
        public java.lang.String getMContent() {
            java.lang.Object ref = mContent_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                mContent_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string mContent = 1;</code>
         */
        public com.google.protobuf.ByteString
        getMContentBytes() {
            java.lang.Object ref = mContent_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                mContent_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string mContent = 1;</code>
         */
        public Builder setMContent(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            mContent_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string mContent = 1;</code>
         */
        public Builder clearMContent() {

            mContent_ = getDefaultInstance().getMContent();
            onChanged();
            return this;
        }

        /**
         * <code>string mContent = 1;</code>
         */
        public Builder setMContentBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            mContent_ = value;
            onChanged();
            return this;
        }

        private long mTime_;

        /**
         * <code>uint64 mTime = 2;</code>
         */
        public long getMTime() {
            return mTime_;
        }

        /**
         * <code>uint64 mTime = 2;</code>
         */
        public Builder setMTime(long value) {

            mTime_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>uint64 mTime = 2;</code>
         */
        public Builder clearMTime() {

            mTime_ = 0L;
            onChanged();
            return this;
        }

        private int mFromId_;

        /**
         * <code>int32 mFromId = 3;</code>
         */
        public int getMFromId() {
            return mFromId_;
        }

        /**
         * <code>int32 mFromId = 3;</code>
         */
        public Builder setMFromId(int value) {

            mFromId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 mFromId = 3;</code>
         */
        public Builder clearMFromId() {

            mFromId_ = 0;
            onChanged();
            return this;
        }

        private int mToId_;

        /**
         * <code>int32 mToId = 4;</code>
         */
        public int getMToId() {
            return mToId_;
        }

        /**
         * <code>int32 mToId = 4;</code>
         */
        public Builder setMToId(int value) {

            mToId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 mToId = 4;</code>
         */
        public Builder clearMToId() {

            mToId_ = 0;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:TTMessage)
    }

    // @@protoc_insertion_point(class_scope:TTMessage)
    private static final cn.dmandp.entity.TTMessage DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new cn.dmandp.entity.TTMessage();
    }

    public static cn.dmandp.entity.TTMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TTMessage>
            PARSER = new com.google.protobuf.AbstractParser<TTMessage>() {
        public TTMessage parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new TTMessage(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<TTMessage> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TTMessage> getParserForType() {
        return PARSER;
    }

    public cn.dmandp.entity.TTMessage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

