// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TTIM.proto

package cn.dmandp.entity;

public interface TTMessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:TTMessage)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mContent = 1;</code>
     */
    java.lang.String getMContent();

    /**
     * <code>string mContent = 1;</code>
     */
    com.google.protobuf.ByteString
    getMContentBytes();

    /**
     * <code>uint64 mTime = 2;</code>
     */
    long getMTime();

    /**
     * <code>int32 mFromId = 3;</code>
     */
    int getMFromId();

    /**
     * <code>int32 mToId = 4;</code>
     */
    int getMToId();
}
