// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TTIM.proto

package cn.dmandp.entity;

/**
 * Protobuf type {@code TTUser}
 */
public final class TTUser extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:TTUser)
        TTUserOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use TTUser.newBuilder() to construct.
    private TTUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private TTUser() {
        uId_ = 0;
        uName_ = "";
        uPhoto_ = "";
        uPassword_ = "";
        uFriends_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private TTUser(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        uId_ = input.readInt32();
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        uName_ = s;
                        break;
                    }
                    case 26: {
                        java.lang.String s = input.readStringRequireUtf8();

                        uPhoto_ = s;
                        break;
                    }
                    case 34: {
                        java.lang.String s = input.readStringRequireUtf8();

                        uPassword_ = s;
                        break;
                    }
                    case 40: {
                        if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                            uFriends_ = new java.util.ArrayList<java.lang.Integer>();
                            mutable_bitField0_ |= 0x00000010;
                        }
                        uFriends_.add(input.readInt32());
                        break;
                    }
                    case 42: {
                        int length = input.readRawVarint32();
                        int limit = input.pushLimit(length);
                        if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                            uFriends_ = new java.util.ArrayList<java.lang.Integer>();
                            mutable_bitField0_ |= 0x00000010;
                        }
                        while (input.getBytesUntilLimit() > 0) {
                            uFriends_.add(input.readInt32());
                        }
                        input.popLimit(limit);
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                uFriends_ = java.util.Collections.unmodifiableList(uFriends_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cn.dmandp.entity.TTIM.internal_static_TTUser_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cn.dmandp.entity.TTIM.internal_static_TTUser_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.dmandp.entity.TTUser.class, cn.dmandp.entity.TTUser.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private int uId_;

    /**
     * <code>int32 uId = 1;</code>
     */
    public int getUId() {
        return uId_;
    }

    public static final int UNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object uName_;

    /**
     * <code>string uName = 2;</code>
     */
    public java.lang.String getUName() {
        java.lang.Object ref = uName_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            uName_ = s;
            return s;
        }
    }

    /**
     * <code>string uName = 2;</code>
     */
    public com.google.protobuf.ByteString
    getUNameBytes() {
        java.lang.Object ref = uName_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            uName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int UPHOTO_FIELD_NUMBER = 3;
    private volatile java.lang.Object uPhoto_;

    /**
     * <code>string uPhoto = 3;</code>
     */
    public java.lang.String getUPhoto() {
        java.lang.Object ref = uPhoto_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            uPhoto_ = s;
            return s;
        }
    }

    /**
     * <code>string uPhoto = 3;</code>
     */
    public com.google.protobuf.ByteString
    getUPhotoBytes() {
        java.lang.Object ref = uPhoto_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            uPhoto_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int UPASSWORD_FIELD_NUMBER = 4;
    private volatile java.lang.Object uPassword_;

    /**
     * <code>string uPassword = 4;</code>
     */
    public java.lang.String getUPassword() {
        java.lang.Object ref = uPassword_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            uPassword_ = s;
            return s;
        }
    }

    /**
     * <code>string uPassword = 4;</code>
     */
    public com.google.protobuf.ByteString
    getUPasswordBytes() {
        java.lang.Object ref = uPassword_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            uPassword_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int UFRIENDS_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> uFriends_;

    /**
     * <code>repeated int32 uFriends = 5;</code>
     */
    public java.util.List<java.lang.Integer>
    getUFriendsList() {
        return uFriends_;
    }

    /**
     * <code>repeated int32 uFriends = 5;</code>
     */
    public int getUFriendsCount() {
        return uFriends_.size();
    }

    /**
     * <code>repeated int32 uFriends = 5;</code>
     */
    public int getUFriends(int index) {
        return uFriends_.get(index);
    }

    private int uFriendsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        getSerializedSize();
        if (uId_ != 0) {
            output.writeInt32(1, uId_);
        }
        if (!getUNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uName_);
        }
        if (!getUPhotoBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, uPhoto_);
        }
        if (!getUPasswordBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, uPassword_);
        }
        if (getUFriendsList().size() > 0) {
            output.writeUInt32NoTag(42);
            output.writeUInt32NoTag(uFriendsMemoizedSerializedSize);
        }
        for (int i = 0; i < uFriends_.size(); i++) {
            output.writeInt32NoTag(uFriends_.get(i));
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (uId_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, uId_);
        }
        if (!getUNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uName_);
        }
        if (!getUPhotoBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, uPhoto_);
        }
        if (!getUPasswordBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, uPassword_);
        }
        {
            int dataSize = 0;
            for (int i = 0; i < uFriends_.size(); i++) {
                dataSize += com.google.protobuf.CodedOutputStream
                        .computeInt32SizeNoTag(uFriends_.get(i));
            }
            size += dataSize;
            if (!getUFriendsList().isEmpty()) {
                size += 1;
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32SizeNoTag(dataSize);
            }
            uFriendsMemoizedSerializedSize = dataSize;
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof cn.dmandp.entity.TTUser)) {
            return super.equals(obj);
        }
        cn.dmandp.entity.TTUser other = (cn.dmandp.entity.TTUser) obj;

        boolean result = true;
        result = result && (getUId()
                == other.getUId());
        result = result && getUName()
                .equals(other.getUName());
        result = result && getUPhoto()
                .equals(other.getUPhoto());
        result = result && getUPassword()
                .equals(other.getUPassword());
        result = result && getUFriendsList()
                .equals(other.getUFriendsList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUId();
        hash = (37 * hash) + UNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUName().hashCode();
        hash = (37 * hash) + UPHOTO_FIELD_NUMBER;
        hash = (53 * hash) + getUPhoto().hashCode();
        hash = (37 * hash) + UPASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getUPassword().hashCode();
        if (getUFriendsCount() > 0) {
            hash = (37 * hash) + UFRIENDS_FIELD_NUMBER;
            hash = (53 * hash) + getUFriendsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static cn.dmandp.entity.TTUser parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.dmandp.entity.TTUser parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.dmandp.entity.TTUser parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.dmandp.entity.TTUser parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.dmandp.entity.TTUser parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.dmandp.entity.TTUser parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.dmandp.entity.TTUser parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.dmandp.entity.TTUser parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.dmandp.entity.TTUser parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.dmandp.entity.TTUser parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.dmandp.entity.TTUser parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.dmandp.entity.TTUser parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(cn.dmandp.entity.TTUser prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code TTUser}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:TTUser)
            cn.dmandp.entity.TTUserOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.dmandp.entity.TTIM.internal_static_TTUser_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.dmandp.entity.TTIM.internal_static_TTUser_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.dmandp.entity.TTUser.class, cn.dmandp.entity.TTUser.Builder.class);
        }

        // Construct using cn.dmandp.entity.TTUser.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            uId_ = 0;

            uName_ = "";

            uPhoto_ = "";

            uPassword_ = "";

            uFriends_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000010);
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return cn.dmandp.entity.TTIM.internal_static_TTUser_descriptor;
        }

        public cn.dmandp.entity.TTUser getDefaultInstanceForType() {
            return cn.dmandp.entity.TTUser.getDefaultInstance();
        }

        public cn.dmandp.entity.TTUser build() {
            cn.dmandp.entity.TTUser result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public cn.dmandp.entity.TTUser buildPartial() {
            cn.dmandp.entity.TTUser result = new cn.dmandp.entity.TTUser(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.uId_ = uId_;
            result.uName_ = uName_;
            result.uPhoto_ = uPhoto_;
            result.uPassword_ = uPassword_;
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                uFriends_ = java.util.Collections.unmodifiableList(uFriends_);
                bitField0_ = (bitField0_ & ~0x00000010);
            }
            result.uFriends_ = uFriends_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cn.dmandp.entity.TTUser) {
                return mergeFrom((cn.dmandp.entity.TTUser) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(cn.dmandp.entity.TTUser other) {
            if (other == cn.dmandp.entity.TTUser.getDefaultInstance()) return this;
            if (other.getUId() != 0) {
                setUId(other.getUId());
            }
            if (!other.getUName().isEmpty()) {
                uName_ = other.uName_;
                onChanged();
            }
            if (!other.getUPhoto().isEmpty()) {
                uPhoto_ = other.uPhoto_;
                onChanged();
            }
            if (!other.getUPassword().isEmpty()) {
                uPassword_ = other.uPassword_;
                onChanged();
            }
            if (!other.uFriends_.isEmpty()) {
                if (uFriends_.isEmpty()) {
                    uFriends_ = other.uFriends_;
                    bitField0_ = (bitField0_ & ~0x00000010);
                } else {
                    ensureUFriendsIsMutable();
                    uFriends_.addAll(other.uFriends_);
                }
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            cn.dmandp.entity.TTUser parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (cn.dmandp.entity.TTUser) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private int uId_;

        /**
         * <code>int32 uId = 1;</code>
         */
        public int getUId() {
            return uId_;
        }

        /**
         * <code>int32 uId = 1;</code>
         */
        public Builder setUId(int value) {

            uId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 uId = 1;</code>
         */
        public Builder clearUId() {

            uId_ = 0;
            onChanged();
            return this;
        }

        private java.lang.Object uName_ = "";

        /**
         * <code>string uName = 2;</code>
         */
        public java.lang.String getUName() {
            java.lang.Object ref = uName_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                uName_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string uName = 2;</code>
         */
        public com.google.protobuf.ByteString
        getUNameBytes() {
            java.lang.Object ref = uName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                uName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string uName = 2;</code>
         */
        public Builder setUName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            uName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string uName = 2;</code>
         */
        public Builder clearUName() {

            uName_ = getDefaultInstance().getUName();
            onChanged();
            return this;
        }

        /**
         * <code>string uName = 2;</code>
         */
        public Builder setUNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            uName_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object uPhoto_ = "";

        /**
         * <code>string uPhoto = 3;</code>
         */
        public java.lang.String getUPhoto() {
            java.lang.Object ref = uPhoto_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                uPhoto_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string uPhoto = 3;</code>
         */
        public com.google.protobuf.ByteString
        getUPhotoBytes() {
            java.lang.Object ref = uPhoto_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                uPhoto_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string uPhoto = 3;</code>
         */
        public Builder setUPhoto(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            uPhoto_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string uPhoto = 3;</code>
         */
        public Builder clearUPhoto() {

            uPhoto_ = getDefaultInstance().getUPhoto();
            onChanged();
            return this;
        }

        /**
         * <code>string uPhoto = 3;</code>
         */
        public Builder setUPhotoBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            uPhoto_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object uPassword_ = "";

        /**
         * <code>string uPassword = 4;</code>
         */
        public java.lang.String getUPassword() {
            java.lang.Object ref = uPassword_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                uPassword_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string uPassword = 4;</code>
         */
        public com.google.protobuf.ByteString
        getUPasswordBytes() {
            java.lang.Object ref = uPassword_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                uPassword_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string uPassword = 4;</code>
         */
        public Builder setUPassword(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            uPassword_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string uPassword = 4;</code>
         */
        public Builder clearUPassword() {

            uPassword_ = getDefaultInstance().getUPassword();
            onChanged();
            return this;
        }

        /**
         * <code>string uPassword = 4;</code>
         */
        public Builder setUPasswordBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            uPassword_ = value;
            onChanged();
            return this;
        }

        private java.util.List<java.lang.Integer> uFriends_ = java.util.Collections.emptyList();

        private void ensureUFriendsIsMutable() {
            if (!((bitField0_ & 0x00000010) == 0x00000010)) {
                uFriends_ = new java.util.ArrayList<java.lang.Integer>(uFriends_);
                bitField0_ |= 0x00000010;
            }
        }

        /**
         * <code>repeated int32 uFriends = 5;</code>
         */
        public java.util.List<java.lang.Integer>
        getUFriendsList() {
            return java.util.Collections.unmodifiableList(uFriends_);
        }

        /**
         * <code>repeated int32 uFriends = 5;</code>
         */
        public int getUFriendsCount() {
            return uFriends_.size();
        }

        /**
         * <code>repeated int32 uFriends = 5;</code>
         */
        public int getUFriends(int index) {
            return uFriends_.get(index);
        }

        /**
         * <code>repeated int32 uFriends = 5;</code>
         */
        public Builder setUFriends(
                int index, int value) {
            ensureUFriendsIsMutable();
            uFriends_.set(index, value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated int32 uFriends = 5;</code>
         */
        public Builder addUFriends(int value) {
            ensureUFriendsIsMutable();
            uFriends_.add(value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated int32 uFriends = 5;</code>
         */
        public Builder addAllUFriends(
                java.lang.Iterable<? extends java.lang.Integer> values) {
            ensureUFriendsIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                    values, uFriends_);
            onChanged();
            return this;
        }

        /**
         * <code>repeated int32 uFriends = 5;</code>
         */
        public Builder clearUFriends() {
            uFriends_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000010);
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:TTUser)
    }

    // @@protoc_insertion_point(class_scope:TTUser)
    private static final cn.dmandp.entity.TTUser DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new cn.dmandp.entity.TTUser();
    }

    public static cn.dmandp.entity.TTUser getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TTUser>
            PARSER = new com.google.protobuf.AbstractParser<TTUser>() {
        public TTUser parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new TTUser(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<TTUser> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TTUser> getParserForType() {
        return PARSER;
    }

    public cn.dmandp.entity.TTUser getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

