// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TTIM.proto

package cn.dmandp.entity;

public interface TTUserOrBuilder extends
        // @@protoc_insertion_point(interface_extends:TTUser)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 uId = 1;</code>
     */
    int getUId();

    /**
     * <code>string uName = 2;</code>
     */
    java.lang.String getUName();

    /**
     * <code>string uName = 2;</code>
     */
    com.google.protobuf.ByteString
    getUNameBytes();

    /**
     * <code>string uPhoto = 3;</code>
     */
    java.lang.String getUPhoto();

    /**
     * <code>string uPhoto = 3;</code>
     */
    com.google.protobuf.ByteString
    getUPhotoBytes();

    /**
     * <code>string uPassword = 4;</code>
     */
    java.lang.String getUPassword();

    /**
     * <code>string uPassword = 4;</code>
     */
    com.google.protobuf.ByteString
    getUPasswordBytes();

    /**
     * <code>repeated int32 uFriends = 5;</code>
     */
    java.util.List<java.lang.Integer> getUFriendsList();

    /**
     * <code>repeated int32 uFriends = 5;</code>
     */
    int getUFriendsCount();

    /**
     * <code>repeated int32 uFriends = 5;</code>
     */
    int getUFriends(int index);
}
